label chap5:
    $save_name = "chap5: psyche"
    $persistent.Chapter5Unlocked = True
    scene bg chap05 with slowdissolve
    with Pause(2)
    scene bg black with fade
    stop music fadeout 2.0
    if openlocket and not rgloves:
        call childish from _call_childish
    else:
        jump fleshyroom
return
    
label fleshyroom:  
    play music "sfx/whisper.ogg" fadein 2.0
    if justice:
        m "Punish him!"
    else:
        m "Take revenge for me!"
    #accompanied by screen shaking
    with Shake((0.5, 1.0, 0.5, 1.0), 1.0, dist=3)
    scene bg rosaroomdark
    "Rosa's hands were over her head."
    "She pressed herself into a corner, panting."
    "She has never heard Mother this loud before."
    if justice:
        m "PUNISHMENT!"
    else:  
        m "Take REVENGE!"
    #More screen shake effects
    with Shake((0.5, 1.0, 0.5, 1.0), 1.0, dist=3)
    "The world rattled around her skull and made her vision blur."
    r "M-Mother…"
    r "What more do you want--?"
    r "The spell is already--"
    "She bent her head, black spots creeping into the edge of her vision."
    "She was so, so tired."
    m "You cannot hide anything from me."
    m "What is this doubt you are nursing?!"
    m "You are hesitating!"
    m "You are crafting another spell!"
    m "You stupid harlot!"
    r "..."
    m "That filthy Marquis is exactly the kind of monster I have been warning you about!"
    m "You dare plan behind my back?"
    r "I..."
    r "I just don't want to kill anymore, Mother."
    "She couldn't help but answer back this time."
    "How could she not?"
    "After years filled with love and acceptance, it made her realise all the more how precious life was."
    "The thought of snuffing out somebody else's life sent a detestable shiver through her bones."
    "She had planned on running away from this place, abandoning whatever duty that now fell on her hands."
    "Why was it her duty anyway?"
    "She just wanted to take the good memories of this place and taint them no longer."
    "Whatever truth she sought wasn't enough payment for peace."
    r "I don't want to."
    "Her voice shook."
    r "I don't want to kill him, Mother."
    r "I don't want to kill anyone, please."
    m "Is this cowardice or stupidity?"
    call fancyg from _call_fancyg

    "With this final proclamation Rosa was struck to the floor."
    "The feeling of fainting was stronger than ever."
    "Alone in the dark she lay there, panting like a sick dog, waiting for what would come next."
    "Catherine's voice squeezed itself into her aching brain."
    cn "Guilleme killed me."
    cn "He made me love him and then he betrayed me."
    cn "He deserves death."
    cn "Only you can kill him."
    r "I..."
    r "I can't kill him."
    cn "It's what I want."
    r "..."
    r "T-That's not true..."
    cn "It is."
    if justice:
        cn "I want to see justice served."
        cn "You'll do that for me, won't you, Rosa?"
    else: 
        cn "You're my best friend, Rosa."
        cn "Friends avenge each other, don't they?"
    mn "{i}My darling daughter…{/i}"
    mn "{i}I could always count on you to do the right thing.{/i}"
    m "So kill him."
    cn "Kill Guilleme."
    m "Kill him."
    mn "{i}Promise me.{/i}"
    cn "Make him suffer."
    m "Stab him with a knife."
    mn "{i}*laughs*{/i}"
    cn "Stick a dagger down his throat."
    m "Gouge his eyes out."
    if justice:
        cn "Execute..."
        m "HIS SENTENCE."
    else: 
        cn "Take…"
        m "REVENGE!"
    #screen shake effects
    with Shake((0.5, 1.0, 0.5, 1.0), 1.0, dist=3)
    "Rosa clutched her head so hard she thought her skull would burst."
    "For a long moment, she lay as though she were dead."
    "Five minutes, ten minutes passed."
    "Then, in the middle of the empty room, Rosa's voice rang out as clear as a bell."
    r "I understand..."
    scene bg black
    $ renpy.pause(delay=None)
    stop music fadeout 3.0      
    scene bg hallway
    play sound "sfx/knock.ogg"
    "Rosa knocked on Guilleme's door, carrying a tray of food."
    "She had been poisoning his meals in small doses for weeks now, taking note of any ill effects it yielded."
    "There had been none."
    "Guilleme was as still fit and healthy as ever."
    "No symptoms at all, even after she had increased the dosage."
    "Either he hadn't eaten anything for a month, or he was immune to poison."
    "Both possibilities were suspect."
    play sound "sfx/knock.ogg"
    "Rosa knocked again."
    "There was no response from the other side of the door."
    r "It may have worked."
    "It was not a total loss, however."
    "She remembered Catherine mentioning how particular Guilleme was with his sleep."
    "Just as she had been about to give up, she had ventured on this hunch."
    "It was true. Guilleme was curiously, rather sensitive to sedatives."
    "Rosa had offered rose tea to Guilleme that afternoon, under the guise that she had made a new recipe."
    "It had been laced with opium and valerian, sweetened with honey to mask the taste."
    "Whether or not it was the casting of Philia, he had drunk it without second thought."
    "He had retired early that evening."
    "Rosa noted the grogginess visible in his gait."
    "She snuck the master key this evening."
    "Tonight is her night."
    play sound "sfx/churchdoor.ogg"
    scene bg guilroomsuperdark
    play music "sfx/womb.ogg" fadein 7.0
    "Rosa pushed the door to his room open."
    $renpy.music.set_volume(0.3, delay=2.0)
    r "..."
    "It took a couple of seconds for her eyes to adjust to the darkness."
    "It felt like a different world inside this room."
    "By closing the door, it was as if she had cut herself off from the living."
    "Rosa took an unsure step once she found her bearings."
    "She placed the tray of food on the nearest flat surface, careful not to make any noise."
    play sound "sfx/matchflare.ogg"
    scene bg guilroomdark
    "The lit candle provided little comfort, it seemed to cower from the intimidating blanket of shadows."
    "Rosa heaved."
    "The air felt humid here, the atmosphere almost... {i}stale{/i}."
    "Now that she was inside and venturing deeper, a sudden impulse to find the exit gripped her."
    "She looked back. The door seemed farther away."
    "Why was she so anxious?"
    "She had been in this room before. It was perfectly normal."
    "But tonight..."
    "The room seemed to {i}breathe{/i}."
    "Rosa gulped. What a curious word."
    "There was no other way to describe it, though."
    "The flickering shadows made it seem like the walls were respiring around her."
    "The room felt alive."
    "It was asleep, like its owner, but alive."
    "In the dim light of her candle, the red carpet looked like flesh."
    "The furnishings were viscera."
    "It didn't feel like she entered a room at all... but a belly."
    "Something darted in the corner of her eye."
    "Rosa snapped her head."
    "..."
    "Just a curtain."
    "Rosa let out the breath she was holding in her chest, aware with every move her body made."
    "She tiptoed towards the canopy."
    $renpy.music.set_volume(0.5, delay=2.0)
    "It was perhaps the highlight of the room, an organic monstrosity of red plush and velvet."
    "From afar, it didn't look like a bed at all, but a cage."
    "If the room was a cavern of meat, then this..."
    "This was its heart."
    $renpy.music.set_volume(1.0, delay=2.0)
    "Rosa approached. Every muscle in her body was tense."
    scene bg guilbedclosebook
    "She could see a figure sprawled on the bed, limbs sticking out clumsily."
    "He was lying on his chest, back bare, clothes littering the floor."
    "Guilleme seemed to have fallen into the bed instead of climbing in."
    "One of his arms stuck out from the mattress."
    "His breath was fitful but slow, a light snore coming from him."
    play sound "sfx/slump.ogg"
    "...!"
    "What was that?"
    "Rosa looked around for the source of the noise, but the room was still."
    "A slow trickle of sweat traced her spine."
    "Did that come from the window?"
    "S-Should she check?"
    "Rosa didn't move."
    "Something was in the room with her."
    "She could feel it."
    "She stole a glance at Guilleme. He hadn't moved from the bed."
    "Rosa's ears tried to pick up the faintest noise."
    "It felt like hours of her staying frozen on that spot, wishing to blend with the darkness."
    "But there was no one there."
    "She had probably imagined it."
    "She took a deep breath and calmed herself down."
    "The sooner she was out of this room, the better."
    "Philia's effect would diminish once the candle died."
    "After that, she might not have another chance."
    "She had to find out more about him tonight."
    "The thought of her goal helped steel her nerves."
    "Where should she begin?"
    "She took a step."
    play sound "sfx/runfast.ogg"
    "...!"
    "Rosa darted her head, looking for the source of the skittering noise."
    "Her ears were too sensitive now."
    "She heard every creak and moan in the room."
    "She took a deep breath."
    "{i}Focus.{/i}"
    "Rosa surveyed everything."
    "There was a book by Guilleme's bedside table."
    "It was only a couple of steps away, but she’d have to come dangerously close to the bed."
    "As much as she could, she'd rather maintain the distance between her and the creature on the bed."
    "..."
    "{i}Creature.{/i}"
    "Why did she think that?"
    "Perhaps it was the arrangement of the sheets, or the shadows playing their tricks, but--"
    "Rosa shook her head."
    "Perhaps there was another place to look?"
    m "We've come here to gather information."
    m "You should check the book."
    r "..."
    "Rosa sighed. Mother was right."
    "She had to check every source to be sure."
    "She inched herself closer to the bed."
    "The faint candlelight indicated that the book on the bedside was red."
    "It wasn't the journal she had seen Guilleme write in."
    "Rosa tiptoed her way closer."
    "Guilleme's hand dangled mere inches away."
    "She reached her arms towards the book."
    play sound "sfx/quietswipe.ogg"
    scene bg guilbedclose
    "And swiped it noiselessly."

    "The candle almost went out with her sigh."
    "She backed up from the bed with the book under her arm."
    "Adrenaline surged in her blood."
    "It almost made her smile."
    "Rosa examined her prize."
    "A book in a foreign language."
    "She remembered seeing such thin obscure characters somewhere."
    "She wasn't sure which country, but it was probably Asian."
    "She flipped the book and saw a piece of parchment folded on one of the pages."
    "A sailing permit for a barge named {i}\"La Victoria\"{/i} dated for the end of the month."
    "Two days from now."
    "It outlined the cargo and the purposes of the trip with no date of return."
    r "Travelling?"
    m "No..."
    m "Leaving..."
    "Guilleme was planning to leave."
    "This was a suspicion she had since she had started observing him."
    "His sudden aloofness with the town affairs."
    "The secret purchase of a ship."
    "The decrease of servants in his employ."
    "Now, it was confirmed."
    m "It's just as well we found this."
    m "We must end it tonight before he has a chance to escape."
    "Althought it was a good thing to confirm this suspicion, the fact helped her little."
    "If anything, it just made it even more urgent to find something tonight."
    "She had to continue."
    "Rosa steadied herself and stepped back to the bed."
    $renpy.music.set_volume(1.0, delay=2.0)
    "Her hand finally brushed against the wood of the table after some quiet fumbling."

    "She caught sight of something shiny inside the drawer."
    m "Open it, child."
    scene bg guilbedopen
    play sound "sfx/opendrawer.ogg"
    "Rosa pulled the drawer open, ever so slightly."
    "She peeked inside."
    scene bg guildrawer
    "Inside was an ornate dagger with a golden hilt, set in with rubies."
    "An old, delicate pattern was carved on its blade."
    "There was a heat emanating from it, almost like it was alive, like the rest of the room."  
    "She almost missed it in the dim light, but there was also a key in the same cabinet."
    call bedside from _call_bedside
    play sound "sfx/creak.ogg"
    $renpy.music.set_volume(0.1, delay=2.0)
    "Guilleme shifted."
    play sound "sfx/breath.ogg"
    scene bg black with None
    "Rosa blew the candle out."
    "She scuttled behind the small table. It barely hid her. "
    "Guilleme had changed positions in his sleep."
    "Now his face was in full view and facing her direction."
    scene bg guilroomsuperdark
    $renpy.music.set_volume(1.0, delay=2.0)
    "Rosa's heart banged in her chest."
    "It was so loud, she was concerned the room might echo the sound and announce her intrusion."
    "Rosa waited for a few minutes before moving."
    "She decided to crouch down, holding the unlit candle close to her chest."
    "{i}Easy now.{/i}"
    $renpy.music.set_volume(0.5, delay=2.0)
    "She shuffled away from the bed in relief."
    scene bg guilroomsuperdark
    "The candle was dead, but her eyes were now well-adjusted to the darkness."
    "She could make out a desk in the furthest part of the room."
    m "He must do most of his writing there."
    m "There is a huge chance the journal is near."
    "It wasn't very dignifying, but Rosa decided to crawl towards it."
    "Now that Guilleme's face was in full view, a flutter of the eyelid was all it would take to catch her."
    "It would be better to minimize her risks."
    "She dropped to her knees and placed her palms on the floor."
    play sound "sfx/gasp.ogg"
    $renpy.pause(delay=None)
    "She drew her hand back."
    "Was she imagining it?"
    "When her palms touched the floor, it felt warm."
    "{i}...Wet.{/i}"
    "Her fingers were sucked into the floor as if she'd touched soft, pulpy flesh."
    "The hallucination was so strong that her nose detected a spray of iron in the air."
    "Her stomach heaved."
    "She rubbed her hand."
    "There was no wetness or blood anywhere."
    "The floor was solid."
    "..."
    "It..."
    "It must have been her imagination."
    "Rosa touched the floor warily, patting it and pulling on the carpet fibers."
    "Just a normal carpet."
    "Rosa let out slow, small breaths as she started to move once more."
    "She padded her way to the desk."
    "Every time her skin came into contact with the floor, bile rose up her throat."
    "It took some effort to resist the urge to gag."
    scene bg guildesk
    "Finally, the desk was directly in front of her."
    "She looked back at the bed."
    "From this angle, it was hard to tell if Guilleme had moved."
    "She hoped that the big desk also hid her in its shadows."
    "Rosa rummaged."
    "There was no trace of the book on the table top, she only found a pot of ink, loose sheets of paper, and a quill."
    "That damn thing had to be close."
    play sound "sfx/opendrawer.ogg"
    "She opened the first shelf and found a stack of papers."
    "Nothing."
    play sound "sfx/closedrawer.ogg"
    "She shuffled through them but the drawer didn't have the journal."
    play sound "sfx/bothdrawer.ogg"
    "She looked through the second drawer."
    play sound "sfx/bothdrawer.ogg"
    "... And the third."
    "There was nothing of interest."   
    "Finally, she pulled on the last drawer."
    play sound "sfx/lockeddrawer.ogg"
    "It was locked."
    "Rosa sucked the air through her teeth."
    r "{i}Of course it's locked! How could I have been so stupid{/i}!?"
    "Rosa slumped in a depressed heap."
    stop music fadeout 20.0
    if dagger:
        m "Why don't you use that dagger to pry the drawer open?"
        r "..."
        "Rosa looked at the sharp dagger in her hand."
        "The idea appealled to her more than returning to the bedside drawer to try the key she didn't take."
        "She shivered."
        "The thought of approaching the bed again made her stomach wind into a tight knot."
        "She might have to try this first."
        play sound "sfx/knifewood.ogg"
        "Rosa positioned the knife to pry open the lip of the drawer."
        play sound "sfx/woodsnap.ogg"
        "The wood wasn't terribly thick."
        "With a little more prying, she felt the wood give under her force."
        "Soon she heard a snap."
        play sound "sfx/opendrawer.ogg"
    else:
        m "The key."
        "Rosa looked at the key in her hand."
        play sound "sfx/freelock.ogg"
        "She slid it into the hole and heard the lock click."
        "A deep feeling of relief washed over her."
        play sound "sfx/opendrawer.ogg"
    "The drawer slid open."
    "Rosa looked inside."
    "There it was."
    "In her eyes, the green journal was a treasure."
    "She lifted the book from its resting place."
    "It was heavier than she expected."
    "Rosa smiled."
    "She ran her hands along the velvet cover of the book, savoring the texture."
    "At last! She had it!"
    scene bg black
    m "Child."
    play music "sfx/scary.ogg"
    show cupidroom
    "Mother's voice was riddled with anxiety."
    m "Something is wrong."
    r "..."
    "Her excitement had clouded her senses."
    "Almost at once, she felt the change in the air."
    "Everything was.... still."
    "Her stomach shrunk into its cavity."
    "Fresh sweat broke out on her scalp."
    "This silence..."
    "It had {i}weight.{/i}"
    "It pressed on her skin and made the air thin in her lungs."
    "Rosa stood up."
    if dagger:
        scene bg rgdreadrosa
        "Another movement stirred the darkness."

        "Were those footsteps?"
        "Rosa froze."
        play sound "sfx/gbeat.ogg"
        "She heard a sigh."
        "A chuckle."
        "A soft, amused whisper."
        scene bg rgdread with Dissolve (3.0, alpha=True)
        $ achievement.grant("The Creature")
        $achievement.Sync()
        bg "{i}I spy--{/i}"
        bg "{i}--With my little eye--{/i}"
        "Her brain fired several commands all at once."
        "But her body was paralyzed by fear."
        "Warm breath tickled her nape."
        "She felt a hand reached out for her neck."
        stop music 
        play sound "sfx/simplegasp.ogg"
        scene bg black with None
        "Rosa turned."
        "There was no one there."
        scene bg fleshdoor 
        "She scrambled from the floor, journal in hand."
        "Her eyes focused on the rim of light bordering the door."
        "She grabbed the knob and half-expected it to be locked."
        "But it turned, and she dashed out of the door, panting." 
        scene bg fleshdooropen with Dissolve (0.3, alpha=True)
        play sound "sfx/churchdoor.ogg"

        "Rosa was sure that any second now, a hand would pull her back into that accursed room--"
        "--a figure would be standing there, grinning from ear to ear."
        bg " {k=2}{i}L{w=0.1}i{w=0.1}t{w=0.1}t{w=0.1}l{w=0.1}e{w=0.1} t{w=0.1}h{w=0.1}i{w=0.1}e{w=0.1}f{/i}{/k}"
        "She was so sure that the words almost materialized."
        "..."
        "Nothing came."
        "Nothing stirred."
        "The room was simply dead."
        scene bg hallway
        "Rosa finally caught her breath."
        "She urged herself to move. There was no time to linger."
        "Despite her shaky legs, she wanted to put as much distance between herself and the room as possible."
        if persistent.dagger1WasReadBefore   is None:
            $persistent.dagger1WasReadBefore  = True
            $persistent.currentLinesRead +=1
    else:
        scene bg guilroomflesh
        "She had to leave."
        "Now."
        "Rosa shuffled her way out of the room."
        "With every step, her legs seemed to stick uncomfortably to the floor."
        "It slowed her movement."
        "One more step."
        "Her whole foot felt like sinking."
        "She held onto a chair and staggered back."
        play sound "sfx/gasp.ogg"
        "It was {i}throbbing{/i}. Musty and red, alive and without skin."
        "The air was filled with the unmistakable stench of fresh meat."
        scene bg fleshdoor
        "Rosa ran to the door."
        "She didn't care that the handle seemed to curl around her fingers."
        "She pushed the door open and spilled into the corridor."
        scene bg fleshdooropen
        play sound "sfx/churchdoor.ogg"
        "Rosa fell to her knees while she heard the door close behind her."
        play sound "sfx/softdoorclose.ogg"
        "It almost felt like the door closed by itself."
        "In her confusion, she couldn't be sure."
        scene bg hallway
        "Rosa's heart pounded heavily in her ribs."
        "Just looking at the doorway of the room made her skin crawl."
        if persistent.key1WasReadBefore   is None:
            $persistent.key1WasReadBefore  = True
            $persistent.currentLinesRead +=1
        
    "Rosa gathered her wits and stared at the journal in her hand."
    "She hoped it would contain the information they needed."
    if persistent.fleshyroomWasReadBefore   is None:
        $persistent.fleshyroomWasReadBefore  = True
        $persistent.currentLinesRead +=1
    call chap6 from _call_chap6
    
    
    
return
