
label epilogue:
    show screen quick_menu
    scene bg black
    play music "sfx/bar.ogg" fadein 3.0
    $ achievement.grant("Modern Day Cupid")
    $achievement.Sync()
    n "I'm not sure what it's all supposed to mean in the long run."
    n "If there's a lesson or whatever."
    gr "I doubt it."
    n "Well, that's love, right?"
    n "It's beautiful."
    n "But fuck, why does it have to hurt?"
    gr "You should put that in your next song."
    gr "*laughs*"
    gr "But I'm pretty sure it wouldn't be original."
    n "Bartender, hit me with another."
    gr "You sure you can drive like that?"
    n "What are you, my mother?"
    gr "Just worrying about you."
    n "Pah. Worry about your career, not me."
    gr "Career's fine. Next album's coming out in six weeks."
    gr "Figured it's about time for me to be famous again."
    n "The hell? You fuckin' show-off!"
    n "But really, congrats on the success."
    n "I am happy for you, no joke."
    gr "Nah, it's not a big deal. I just sing."
    n "Yeah, yeah."
    n "At least one of us made it big, right?"
    gr "You still meet up with the guys?"
    n "No, haven't heard from them. Last I talked to Terry, he's on the way to the UK."
    gr "Oh really? Good for him."
    n "Yeah."
    gr "So, what are you up to now?"
    gr "You know, other than being dumped?"
    n "Shut it, asshole."
    n "..."
    n "Nothing much, still teaching rich kids that \"{i}Every Good Boy Does Fine{/i}\"."
    gr "Do they?"
    n "What?"
    gr "Do good boys do fine?"
    n "Never."
    gr "Haha."
    gr "So how is everybody? I haven't been in town for a while."
    n "Oh, small towns never change, fortunately or not, so you haven't missed much."
    n "Big Al and Timmy are missing you at the shelter, though."
    gr "Oh! It has been ages, hasn't it? You still volunteering?"
    n "Yeah, yeah. You should stop by sometime."
    n "..."
    n "I guess I've been going there more often recently. They're probably sick of my face by now."
    n "..."
    n "Ever since Diana left, I've been trying to work things out on my own."
    n "I can't be depressed. I still have Amanda with me."
    gr "Hm.. And how is my little godchild?"
    n "Turning five soon!"
    gr "Wow! She was so small when I last saw her."
    n "There she is. I took a photo of her this morning."
    gr "Aww... She's beautiful."
    gr "That's great, Nathan."
    gr "Glad to see you're hanging tough."
    gr "The folks in the shelter are probably grateful. They need you there."
    n "I'm afraid it isn't totally altruistic."
    n "When I help people out, it's like my own troubles don't seem that hard."
    n "It gives me purpose."
    n "I guess, I have a pretty shitty life..."
    n "But if I can make someone else's better, then I might not be so bad."
    gr "..."
    gr "I've always liked that about you."
    gr "Salt of the earth, shirt-off-my-own-back kind of guy."
    n "Oh yeah?"
    n "..."
    n "Diana doesn't think so."
    gr "..."
    n "Sometimes I think I'm alright, you know."
    n "I'm not bad looking. I'm not dumb, either. I work hard. I try to be--"
    n "...I'd like to think I'm a good person, most of the time."
    n "I'm alright, you know... I'm alright."
    n "Not great, but I try."
    gr "..."
    n "\"You mean nothing to me.\""
    n "Do you know how much those words could hurt?"
    n "It seems..."
    n "Being a good person doesn't stop you from being worthless."
    gr "You shouldn't equate your worth to what other people think."
    gr "People will always judge. You can't stop that--"
    n "But she was supposed to be--"
    n "I thought--"
    n "..."
    gr "..."
    n "Ah well."
    n "As long as Mandy still thinks her daddy makes the best pancakes in the world, I guess I'll be fine."
    n "..."
    gr "For what it's worth, it doesn't change my mind about you."
    gr "I still think you're pretty great."
    n "Heh. You better."
    n "I did clean after your mess a lot of times back then."
    gr "Of course. I wouldn't have survived this era without you."
    gr "I am eternally grateful."
    n "You're exaggerating again."
    gr "No, no."
    gr "I don't think I've said this before, but you're one of the best guys I've ever met, Nate."
    n "Are you teasing me again?"
    gr "I'm serious."
    gr "A bit of a dumb fuck when it comes to romance, but you got your heart in the right place."
    n "Gee, thanks."
    gr "Didn't I tell you Diana was bad news? You should've gone with Kristie."
    n "Kristie?"
    n "She wouldn't give me the time of day, man. Married now, with twins!"
    gr "It's because you're a dumbass. I could've set you up, but you went for Diana."
    gr "When I give you advice, you take it, alright? I'm good with these things."
    n "The heart wants what it wants, dude."
    gr "Bullshit."
    n "That's how love is supposed to be, isn't it?"
    gr "Like I said. Dumbass."
    n "Well, if you're such an expert, go ahead and enlighten me."
    gr "What?"
    n "What's love to you, then?"
    gr "Love?"
    n "Why are you laughing?"
    gr "Based on experience, drunk people only talk about the same things."
    gr "Love and regrets."
    gr "Most of the time, together."
    n "Oh, so what?"
    n "You're dodging the question."
    gr "I didn't haul ass all the way here to talk about cliches, Nathan."
    n "Humor me. I'm paying for your drink."
    gr "Oh, fine."
    gr "Hm."
    gr "What I think about love?"
    gr "I think..."
    gr "I don't need it too much these days."
    gr "There are so many stimulations and distractions in the modern world that it makes things pretty convenient for me."
    gr "Work keeps me busy." 
    gr "My fans give me all the love I need."
    gr "There you go."
    n "That is a fucking cop-out of an answer, if I ever did hear one."
    gr "I'm serious."
    gr "The Twitter fanmail alone is awesome."
    n "You never change, man."
    n "Back then, you got the whole campus all over you."
    n "You were the worst roommate! The worst!"
    n "Did you even have a girlfriend or something?"
    n "I can't seem to remember."
    gr "Well..."
    gr "I did have you, didn't I?"
    n "..."
    n "So I was your bitch, is that what you're saying?"
    gr "Of course not, Nathan! How crass."
    gr "I'd say you were more of my pet."
    n "Ugh, motherfucker!"
    gr "Haha!"
    n "So who are you with now?"
    gr "Nobody."
    gr "I told you. I'm busy."
    n "Weren't you banging, who's that chick--the model--"
    gr "Maria Leigh?"
    n "No, the other one--"
    gr "Gotta be more specific, man."
    n "Very smooth, you fucking bastard."
    gr "I'm unattached right now, that's the truth."
    gr "Unless I see somebody I like, then I get to play a bit."
    gr "I show them a good time. Leave early. Everybody happy."
    n "..."
    n "That's gotta be tough."
    gr "Oh, they'll be fine."
    gr "Nobody gets hurt."
    n "No, I mean, for you."
    gr "Huh?"
    n "I tried that before. One night stands and shit, lots of girls with lots of crappy sex."
    n "Fuckin' lonely."
    gr "It's only lonely if you don't have other hobbies."
    n "Well, I can't handle it."
    n "Maybe I'm just not built that way."
    n "We all need some sort of companionship beyond the physical attachment."
    n "Makes the bad sex bearable, at least."
    gr "Why, Nathan, I didn't know you were such a romantic."
    n "Shut up, it's true."
    n "Humans need love."
    n "If not, then all you're doing's some sort of complicated masturbation."
    n "...No offense. I mean, if that's how you roll."
    n "To each his own, right?"
    n "But..."
    n "Don't you get scared you'll end up alone?"
    gr "..."
    gr "You get used to it."
    n "Liar."
    gr "..."
    n "Well, I {i}do{/i} get scared."
    n "It's like, a thing that’s constantly hovering at the back of my mind."
    n "I don't even know why it even scares me at all."
    n "{i}Being alone.{/i}"
    n "It sounds like a kid's fear."
    n "But maybe that's it, isn't it?"
    n "It's all just fear."
    gr "..."
    gr "No."
    n "Huh?"
    gr "I don't think so, and neither should you."
    gr "I think I get it now."
    gr "Fear doesn't cancel out love."
    gr "It shouldn't."
    n "..."
    gr "What I think about love?"
    gr "Love is... the reason why humans are what they are."
    gr "Not fear. Never fear."
    gr "Otherwise, we would've been extinct eons ago."
    gr "Love makes us idiots."
    gr "...But it also enriches us and makes us more than what we are."
    gr "I thought it's what made humans weak, but the contrary is true."
    gr "Nothing is stronger than something that can change and adapt."
    gr "The true kind of love will hurt and change us, for better or worse."
    gr "Otherwise, there's no point."
    n "..."
    gr "...But love is a drug. It's addictive."
    gr "It's got the same highs and lows as heroin."
    gr "Gotta be careful with how much you take, Nathan."
    gr "Or you'll get screwed."
    gr "Before you know it, you'll be sitting in a bar getting shitfaced, while your wife of seven years leaves you for another man."
    n "For a second there, I thought you were onto something."
    n "But really, you're just a fucker."
    gr "Why, thank you, I try."
    gr "Haha!"
    gr "So for me, I try to get love from different places now."
    gr "Just one person can't handle me."
    gr "Or rather, nobody should."
    n "..."
    n "Maybe you're overestimating yourself."
    gr "Not really."
    n "Well, then..."
    n "Maybe you're underestimating people."
    gr "..."
    gr "I can't do it, Nate."
    n "Hm?"
    gr "I..."
    gr "I tend to give everything to somebody I fall for."
    n "Hm..."
    gr "But I take everything from that person as well."
    gr "It hasn't been easy..."
    gr "Old habits die hard."
    n "..."
    gr "I remember my daughter..."
    n "Woah, woah, woah! Now, this is A-grade news!"
    n "You have a daughter?! Since when? How come I've never heard of this?"
    gr "...Well..."
    gr "She's more an adoptive daughter than anything."
    gr "Nevertheless, she's such a great kid."
    gr "Called me off on this whole stupid exchange thing."
    gr "Parents love their children without exchange..."
    gr "Like we love people who have long since passed on."
    gr "Or how we love people who won't or can't love us back."
    n "..."
    n "Well, that is a pretty smart kid."
    gr "Dunno where she is now though."
    gr "We haven't seen each other in a while... but she changed my life."
    n "..."
    n "Do you miss her, your daughter?"
    gr "..."
    gr "Oh, I'll bump into her sooner or later..."
    gr "...I'm sure she knows where I am. The world's gotten really small."
    n "..."
    n "Hey, mind if I ask you something?"
    gr "Yeah?"
    n "Are you gay?"
    gr "Why, Nathan..."
    gr "After all this time, I thought you'd never ask!"
    n "Quit screwing, man."
    gr "No, I'm not gay. Why?"
    n "Well..."
    n "Our bartender has been giving you some really wet looks, if you know what I mean."
    n "I just thought I'd let you know."
    gr "Oh, why? You jealous?"
    gr "I went out to drink with you, Nathan, so you have my full, undivided attention."
    n "N-No... That's not what I--"
    n "Ugh. You keep fucking with me, man."
    gr "Haha!"
    gr "Sorry... It's a habit."
    gr "Well, he's probably just interested because I've been smiling at him a lot."
    gr "He's quite attractive, don't you think so?"
    n "Err... You said--"
    gr "I'm not gay."
    gr "But I'm not straight either."
    n "Huh?"
    gr "Gender's not the most interesting or complicated thing about humans, Nate."
    gr "Like, I once dated a woman who painted her whole kitchen blue because she was on a diet. No, really!"
    gr "Or there was this guy I met who made it his life's purpose to learn every swear word, 
    in every language, so he could properly cuss people out."
    gr "*laughs*"
    gr "After a while, it seemed silly to base my criteria on it anymore."
    gr "To me, the world's just starting to catch up."
    n "Uhm..."
    n "Err... Alright then."
    n "..."
    n "So have you, uhm..."
    n "Have you legit been hitting on me all this time or something?"
    gr "I'm not sure, Nathan."
    gr "You're the one who called me and asked for a date."
    n "A date--? N-No!"
    n "I just thought it'd be nice to, you know, get together for old times' sake!"
    n "I haven't seen you in years."
    n "...Actually you look really great, it's like you didn't age at all."
    n "Your face is still what I remember--"
    gr "Oh, so {i}now{/i} you're hitting on me, then? Describing my face from your fond memories?"
    gr "My, my. Pretty soon you'll be singing me sonnets!"
    n "Hey, cut it out!"
    gr "Haha! But it's too fun seeing you go red like that."
    n "Geez, I feel like a toy or something..."
    gr "..."
    gr "I'm sorry. I'll stop."
    n "I-It's fine... I'm not angry..."
    n "I'm sorta used to it."
    gr "..."
    n "You know, you never take anything seriously, like ever?"
    n "Everything's a joke to you."
    n "Including me, I guess. Heh..."
    gr "..."
    n "And yet..."
    n "For some bizarre-ass reason, you've always been there for me."
    n "Through the years, every time I need you, it's like you drop everything and appear at my doorstep."
    n "You're always there. {i}Always.{/i} Without fail."
    n "I dunno..."
    n "Sometimes I think to myself: How weird it is that you, {w}\nYou flighty, immature, random-ass motherfucker.."
    n "How can you be one of the most constant things in my life?"
    n "How'd it come to this?"
    n "{i}*laughs*{/i}"
    n "Boggles the mind."
    n "So yeah, I don't really get you most of the time..."
    n "But I'm okay with it."
    gr "..."
    gr "*exhales*"
    gr "F-Fuck... {w=0.3}{i}*glug*{/i}"
    gr "..."
    gr "Whatever."
    gr "You're a grown man, right? You can take it."
    n "What? What the hell do you mean?"
    gr "Nate, I... {w=0.2}I do like you. I always have."
    gr "But I didn't want to ruin a good thing, you know?"
    n "A-Are you still messing with me? If you are, it's not funny anymore."
    gr "..."
    gr "It's true."
    gr "But it's not a big deal. I'm not expecting anything."
    n "..."
    gr "I just wanted you to know that you don't have to be special or exceptional to be loved."
    gr "You're good like that... Just the way you are."
    gr "And just because your wife didn't love you, doesn't mean nobody else would."
    gr "I could..."
    gr "If you want me to."
    n "..."
    n "..."
    gr "Nathan? Are you uncomfortable right now?"
    n "..."
    n "I-I don't know..."
    n "...Not really."
    n "..."
    n "No, no. It's cool."
    n "Uhm..."
    n "T-Thanks, I guess?"
    n "..."
    n "B-But just for the record, I-I'm straight as a whistle!"
    n "So I'm not sure wh---{nw}"
    n "..."
    n "....."
    n "..."
    gr "...I would lay off that next shot if I were you."
    gr "Good things are better enjoyed sober."
    n "..."
    gr "Look at you with that dumbass face."
    gr "{i}*laughs*{/i}"
    gr "Better gear up, Nate. That was just a kiss."
    gr "Plenty more to get embarrassed about later. Heh."
    n "..."
    gr "Come on. Let's get out of here."
    n "Uhm... S-Sure.."
    n "But where are we going?"
    gr "To the best night of your life."
    gr "You just relax."
    gr "I'll drive."
    stop music fadeout 3.0
    $renpy.pause(delay=None)
    if persistent.epilogueWasReadBefore   is None:
        $persistent.epilogueWasReadBefore  = True
        $persistent.currentLinesRead +=1
    $renpy.call_screen("extra_bonus")

return
